### ISSUE TITLE
Custom LRS Landing Page

### ISSUE THREAD

**Issue by acoard-aot** [bcgov/nr-epd-digital-services#107]
**Describe the task**

The LRS login page should include custom branding and styling similar to TAFT.

Example: https://web-test-taft.apps.silver.devops.gov.bc.ca/

**Designs Link**
https://www.figma.com/file/gzF7SL5xpYr5PIY4FyE1TF/Internal-SITE%2FCATS?node-id=258%3A981&t=9P8vJg4ZxT158Q0B-0
![image](https://user-images.githubusercontent.com/104386035/203393268-b79ef9b0-e4f2-485d-a9af-69e657ca59fb.png)

**Acceptance Criteria**
- [x] Custom login page allows for staff to login via IDIR
- [x] Has public user login
- [ ] UI/UX Design Approval

**Additional context**
- ...

**Comment by acoard-aot** [comment]
Closing this task, as I've merged it into #111 and #106, the actual stories for it.

**Comment by RyanBirtch-aot** [comment]
CSS Complete, login not working due to known config issue

https://6d4f-2604-3d08-6386-400-88a9-958a-1a71-26a9.ngrok.io

can use link above for verification of responsiveness

**Comment by nikhila-aot** [comment]
merged to dev
