### ISSUE TITLE
Refine Personas

### ISSUE THREAD

**Issue by acoard-aot** [bcgov/nr-epd-digital-services#11]
**Describe the task**
Refine personas down to a handful, like 2-3, for each of external/internal.  This is to follow UX best practices and make handling personas more manageable.  We can always review to the full list when relevant.

Personas are themes found in qualitative data about our users. They're our best guess of the key users types to focus on in design.

It's generally better to create personas with a more targeted scope of focus, so that the data collected and the resulting personas can have a more direct influence on the designs you intend to create. 

For example: 

* External:  Standard users, QSAP/CSAP
* Internal:  Staff, manager, SDM

**Acceptance Criteria**
- [x] Personas are refined to a more manageable number.

**SME/User Contact**
(may want to use a persona to fill this in)

**Additional context**
- any additional details that could not be captured above

**Comment by mariaye-aot** [comment]
![Persona 1.png](https://images.zenhubusercontent.com/6324b5464682198942bee166/b1113daf-7273-42ea-9825-874ecaf4909b

**Comment by mariaye-aot** [comment]
![Persona 2.png](https://images.zenhubusercontent.com/6324b5464682198942bee166/161bdc15-20e0-47f3-a1a6-68a53a3c9d2d)

**Comment by mariaye-aot** [comment]
![Persona 2.png](https://images.zenhubusercontent.com/6324b5464682198942bee166/a3d3a3b1-d496-44b9-a577-e90ca699b070)

**Comment by mariaye-aot** [comment]
![Persona 3.png](https://images.zenhubusercontent.com/6324b5464682198942bee166/da0df004-ce56-42e1-abf2-9824f4f1caea)
