### ISSUE TITLE
As an external user, I can edit my profile page

### ISSUE THREAD

**Issue by acoard-aot** [bcgov/nr-epd-digital-services#125]
**As a** *external user* **I want** *to view and edit my profile page* **So That** *my information is up to date for all applications*

**Not in scope**
- Implementation of hi-fi designs for this.  This task is just about technical implementation.
- Out-of-BC users.  That should be another task.  Assume BC / Canadian addresses in this task.

**Additional Context**
- If there is any info from Keycloak (like BCeID or BCSS JWT), then we should use that to pre-fill the profile page during account creation
- https://github.com/bcgov/sso-keycloak/wiki/Identity-Provider-Attribute-Mapping
- Will create future tasks to implement designs for this story once the designs are done.
- Content of profile page should be same as contact info pre-amble in multiple CHEFs forms.  So can review CHEFs forms to see what profile fields we need.  See comments for screenshot.
- Can use BC Gov Geocoder for address completion  - https://www2.gov.bc.ca/gov/content/data/geographic-data-services/location-services/geocoder

**Acceptance Criteria**
- [x] Given the user is logged in and on their account details screen, When the user updates their contact info, Then info is expected to persist regardless of what their upstream Identity Provider says (eg if BCeID email is out of date and user provides one, we should use the provided email).
- [x] Given the user has just registered via BCeID, and the BCeID API has contact information data (like email address), then the profile contact info should be auto-populated (but still needs to be confirmed by user).  (NOTE: DO NOT LET IDIR USERS CUSTOMIZE CONTACT INFO.  IDIR MUST BE READ-ONLY FOR SECURITY PURPOSES.  NEED TO REVIEW BC SERVICES CARD HERE.  BIZ BCeID SHOULD HAVE SOME FIELDS LOCKED DOWN LIKE BIZ NUMBERS, BN9).
- [ ] Given the user is on their profile page, When they start filling an address, Then we should use BCgov Geocoder - https://www2.gov.bc.ca/gov/content/data/geographic-data-services/location-services/geocoder

**Designs**
https://www.figma.com/file/gzF7SL5xpYr5PIY4FyE1TF/Internal-SITE%2FCATS

**Definition of Done**
- [x] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [x] Documentation and/or scientific documentation exists and can be found
- [x] Peer Reviewed by 2 people on the team
- [x] Manual testing of all PRs in Dev and Prod
- [x] Merged

**Comment by RyanBirtch-aot** [comment]
https://github.com/bcgov/sso-keycloak/wiki/Identity-Provider-Attribute-Mapping

**Comment by acoard-aot** [comment]
![image.png](https://images.zenhubusercontent.com/6081a3d1bee65b11f6b36f46/3bdcfd9e-e6af-47bb-8c75-d8dc82c5f018)

**Comment by acoard-aot** [comment]
Also include FN status question.  

@mariaye-aot can you please document any other fields that have been confirmed like license numbers and the logic around those?
