### ISSUE TITLE
ETL tools - are there BCGov tools, or consensus / code to leverage, or would we custom code?

### ISSUE THREAD

**Issue by acoard-aot** [bcgov/nr-epd-digital-services#136]
**Describe the task**
This is related to Oracle access, ticket #77.

We will potentially need ETL tools to integrate with the Oracle db.  Are there "blessed" or commonly used ETL solutions in the BCGov space we should consider?  If there is now BCGov tooling/recommmendations, we can always come up with alternatives.  This task is not about fully speccing out our ETL needs, only about identifying if there is pre-existing BCGov ETL work we should leverage.

**Acceptance Criteria**
- [x] Question: Are there "approved" (or even commonly used) ETL tools in the BCGov openshift community?

**Comment by nikhila-aot** [comment]
trying to use ora2pg for schema migration. Stuck with configuration issues. Alternative is to use oracle ddl as input and generate equivalent postgres ddl using ora2pg

**Comment by nikhila-aot** [comment]
able to migrate oracle schema to a sql file compatabile with postgres using ora2pg. Errors for spatial data migration.

**Comment by nikhila-aot** [comment]
We haven't found any concrete answers about any tools specifically used for oracle to postgis migration though we did get suggestions on using ora2pg. 
- [ ] https://chat.developer.gov.bc.ca/channel/devops-how-to/thread/yeGP3npshAi3RYxiC?msg=TZTgAontsBAgu3YHH

**Comment by nikhila-aot** [comment]
ora2pg looks promising for migrating oracle schema (including spatial types) to postgis, have tried to simulate the use in local machine using mock tables in oracle
