### ISSUE TITLE
 Frontend handle API request and show submission result

### ISSUE THREAD

**Issue by acoard-aot** [bcgov/nr-epd-digital-services#159]
**Describe the task**
Related to #125

**Acceptance Criteria**
- [x] Frontend submit to API
- [x] Show success and failure toasts (error handling)
- [x] Include BCgov geocoder - https://bcgov.github.io/ols-devkit/ols-demo/index.html
- [x] Must be able to enter out of BC addresses with geocoder

**Comment by nikhila-aot** [comment]
closing this as we decided not to go for address autofill
