### ISSUE TITLE
Create LRS Architecture

### ISSUE THREAD

**Issue by acoard-aot** [bcgov/nr-epd-digital-services#18]
**Describe the task**
Create architecture diagrams for proposed future state of LRS

Diagrams can be created in something like draw.io, or your favourite design tool of choice.

**Acceptance Criteria**
- [ ] Architecture diagram(s) created for future state.

**Additional context**
- Formsflow.ai or native development?  Can have a few options if appropriate.
- Need to have team agree on architecture, but that can be this ticket or another one as appropriate.

**Comment by acoard-aot** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPD-LRS-Product-630e5ae59b8efb002559b38e/issues/bcgov/nr-epd-digital-services/18?planning-poker) with Zenhub @mariaye-aot @midhun-aot @mishraomp @nikhila-aot @RyanBirtch-aot @sakthi-aot

**Comment by nikhila-aot** [comment]
here is a link to the initial architecture diagram
- https://drive.google.com/drive/folders/1zer82N0ebjR6gabjP8CtPFGqsmiH7oXK

**Comment by acoard-aot** [comment]
Just looked over it a bit but looks really good.  I think the github wiki is a logical place to store this, if we want to think about that.  We might have to export it as a png first.
