### ISSUE TITLE
Alter/Fix/Initiate Intro CI/CD Pipeline

### ISSUE THREAD

**Issue by RyanBirtch-aot** [bcgov/nr-epd-digital-services#20]
**Describe the task**
Start preliminary work on CI/CD pipeline working with existing templates

**Acceptance Criteria**
- [ ] Review existing CI/CD scripts in .github/workflows.  What do the files do?
- [ ] Setup GitHub secrets (eg OpenShift deploy envs)
- [ ] Make sure all CI/CD scripts from the devops template are functioning (or removed if we decide against using that particular script)
- [ ] Communicate the CI/CD scripts effects to team, so we can use/modify/delete as appropriate.

**Additional context**
- Can ask Adam for help on setting up OpenShift deploy envs if needed, he has done so on another project.
- https://github.com/bcgov/nr-epd-digital-services/tree/main/.github/workflows
- https://github.com/bcgov/nr-epd-digital-services/blob/main/SETUP.md

**Comment by acoard-aot** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPD-LRS-Product-630e5ae59b8efb002559b38e/issues/bcgov/nr-epd-digital-services/20?planning-poker) with Zenhub @hsawyerPO @mariaye-aot @midhun-aot @mishraomp @nikhila-aot @RyanBirtch-aot @sakthi-aot

**Comment by acoard-aot** [comment]
@mishraomp please setup meeting with Derek Roberts for setup info.  Thanks.

**Comment by acoard-aot** [comment]
Need to discuss Org-wide GITHUB_TOKEN with @mishraomp  on Tuesday
