### ISSUE TITLE
Testing Framework Choices - Frontend

### ISSUE THREAD

**Issue by RyanBirtch-aot** [bcgov/nr-epd-digital-services#21]
**Describe the task**
Choose and develop early unit testing and UI automation testing

**Acceptance Criteria**
- [x] Determine Unit Testing Framework
- [x] Determine Code Coverage Testing
- [ ] Automated UI Testing Framework Decision

**Additional context**

**Comment by mishraomp** [comment]
My personal vote would be jest for unit testing and either cypress or testcafe for e2e testing.

**Comment by nikhila-aot** [comment]
Unit testing for front end  - prefer to use react testing framework @RyanBirtch-aot

**Comment by RyanBirtch-aot** [comment]
Yes, Requires much less configuration, includes code coverage, and is built in to CreateReactApp boilerplate project. We can assess if we end up needing more functionality.

https://testing-library.com/docs/react-testing-library/intro/

**Comment by acoard-aot** [comment]
We can circle back on Automated UI testing framework later, for now we've answered what we need.  Marking as completed after standup discussion.
