### ISSUE TITLE
Setup Forms & Workflow Engine in Local machine

### ISSUE THREAD

**Issue by midhun-aot** [bcgov/nr-epd-digital-services#216]
**Describe the task**
Deploy Formsflow.ai in local machine (without analytics

**Acceptance Criteria**
- [x] Able to create, draft, submit and edit forms
- [x] Able to upload any one of the chefs form
- [x] Enable SSO

**Comment by nikhila-aot** [comment]
we were able to upload 4 out of the 8 chefs forms in our local machines. Separate tickets will be created to work on rest of the chef form upload
