### ISSUE TITLE
Modify CHEFS form json

### ISSUE THREAD

**Issue by nikhila-aot** [bcgov/nr-epd-digital-services#227]
**Describe the task**
A task to update the chefs form json to make it compatible with formsflow

**Acceptance Criteria**
- [x] update all 8 (as needed) chefs forms and confirm the upload
- [x] ensure the functionalities remain the same (compare with the existing public chefs forms)

**Comment by acoard-aot** [comment]
If we want, we can split this task into future tasks for any remaining forms.

**Comment by nikhila-aot** [comment]
all 8 chefs forms updated and compatible with formsflow
