### ISSUE TITLE
Validate Form Recreation

### ISSUE THREAD

**Issue by RyanBirtch-aot** [bcgov/nr-epd-digital-services#228]
**Describe the task**
After fixing the json in order to upload correctly into formsflow, validate the conditional form aspects function correctly

**Acceptance Criteria**
- [x] CSSA
- [x] Detailed Ecological Risk Assessment Checklist
- [x] Notification of Independent Remediation
- [x] Notification of Likely or Actual Migration
- [x] Protocol 6
- [x] Site Disclosure Statement
- [x] Site Information Request Application
- [x] Site Risk Classification Report

**Additional context**

**Comment by nikhila-aot** [comment]
all forms verified and tested with formsflow upload
