### ISSUE TITLE
Create custom dashboard placeholders

### ISSUE THREAD

**Issue by acoard-aot** [bcgov/nr-epd-digital-services#230]
**Describe the task**
Create custom dashboard placeholders.  These are placeholders and should not have any significant content in them.  The purpose is to setup the boilerplate so that we can create these once designs are completed.

We should try and make sure RBAC is properly followed, and only appropriate roles (setup in Keycloak) can see appropriate dashboards.

**Acceptance Criteria**
- [x] Add link back to react app
- [ ] Custom staff dashboard and link in menu bar
- [ ] Custom manager dashboard and link in menu bar

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by midhun-aot** [comment]
Added a separate role for SDM Dashboard. So reviewer and manager will have 2 separate dashboards
