### ISSUE TITLE
Change from Postgres to Postgis in Openshift

### ISSUE THREAD

**Issue by nikhila-aot** [bcgov/nr-epd-digital-services#249]
**Describe the task**
A task to change from the current Postgres installation in DEV environment to Postgis

**Acceptance Criteria**
- [ ] PostGIS functions are deployed on OpenShift
- [ ] Changes are stored in code/git, deployed to all environments we have setup

**Additional context**
- After meeting with Om, saw Crunchydata uses PostGIS and also helps with HA, so went with that.

**Comment by acoard-aot** [comment]
After meeting with Om, using CrunchyData for PostGIS
