### ISSUE TITLE
User Session Management

### ISSUE THREAD

**Issue by mishraomp** [bcgov/nr-epd-digital-services#28]
**Describe the task**
How do we manage user session? do we need to use express session backed by Redis or just using jwts is sufficient.

**Acceptance Criteria**
- Decision made on the approach.
- what is the finishing point or end state of this task?
-  As a team we agreed to choose which route to take for session management,

**Additional context**
- both approaches have it pros/cons, need to discuss as a team which suits best for us.

**Comment by acoard-aot** [comment]
Frontend: Can store local user session info to LocalStorage.  Then use tokens.

Also cf "deep linking", if refreshing on a nested route or something. 

Midhun, will explore more page refresh style for React Redux.

**Comment by midhun-aot** [comment]
Redux configureStore has option to pass initial state while setting up the store. we can save the user session info in session storage in browser and then fetch and pass it to configureStore at the time of initial store init.

**Comment by midhun-aot** [comment]
We used the package https://github.com/authts/react-oidc-context which internally uses oidc-client-ts package. This package itself provides a UserManager class to manage and persist user sessions at client side
