### ISSUE TITLE
Researching feasability of form bundling with form.io

### ISSUE THREAD

**Issue by RyanBirtch-aot** [bcgov/nr-epd-digital-services#290]
This task is to help determine how to implement form bundling with form.io. 

- [ ] Review formio source code
- [ ] Identify where to put custom metadata for packaging
- [ ] Add any actionable steps learned from this research task to #291 and estimate before closing this task

**Comment by acoard-aot** [comment]
Marked as closed, going with building into formsflow as native feature.
