### ISSUE TITLE
Create Proposed SDS Workflow (originals in Mural)

### ISSUE THREAD

**Issue by acoard-aot** [bcgov/nr-epd-digital-services#293]
**Describe the task**
Duplicate the SDS workflow in the workflow Mural (check sprint Figma), then modify it to be the "proposed future" flow.  Then we can show this flow to Kerri for input.

**Acceptance Criteria**
- [x] SDS workflow with proposed changes of new workflow is created and annotated with explanations for Kerri
- [ ] Once proposed workflow is reviewed and approved, make sure to document it.

**Comment by nikhila-aot** [comment]
updated diagram with expectations on individual form workflow required for April

**Comment by nikhila-aot** [comment]
walkthrough done with Kerri, hence closing
