### ISSUE TITLE
Automated DB Deployment

### ISSUE THREAD

**Issue by mishraomp** [bcgov/nr-epd-digital-services#30]
**Describe the task**
Automate database deployments(schema changes et..) by using  (flyway or liquibase or something similar) as init containers of openshift...)

This is about schema migrations.

**Acceptance Criteria**
- [ ] what is required for this task to be complete?
Agreeing on which tool to use for db deployments and which pattern to use(init containers or within app)
- what is the finishing point or end state of this task?
- Decision made on both aspects.

**Comment by acoard-aot** [comment]
Might use TypeORM synchronize, or whatever gets DB migrations in place.

**Comment by acoard-aot** [comment]
Need TypeORM research, does it have proper rollback migrations, does it work fine when deploying HA?

**Comment by mishraomp** [comment]
This issue is not yet resolved but could give us some idea if moving forward with typeorm.
https://github.com/typeorm/typeorm/issues/4588

**Comment by nikhila-aot** [comment]
I would still favour using TypeORM migrations. We could do a test deployment once the OpenShift environment is setup and see for ourselves
