### ISSUE TITLE
Dev Research - Esra Integrations with SITE

### ISSUE THREAD

**Issue by acoard-aot** [bcgov/nr-epd-digital-services#31]
**Describe the task**
Investigate the Esra Integrations with SITE.  They have made some integrations which we are expected to play nice with.  What are those integrations? How can we accomodate them?

Important question: Are we integrating with new ESRA system? Or Old SITE system? Both?  Need to find boundaries between these two.  Does ESRA have all data and can forward from SITE? Write or read only?

**Acceptance Criteria**
- [x] Report back on Ezra integrations at a technical/API level.
- [x] Store documentation in centralized project area.

**Additional context**
- Haley has a demo video she can try to share.
-

**Comment by mishraomp** [comment]
here is the link to the source code, it is deployed to openshift. I can provide namespace access to the team.
https://github.com/bcgov/nr-site-bc-registries

**Comment by acoard-aot** [comment]
Architecture and documentation has also been emailed and I've moved it to a protected folder.  I'm unsure if this documentation is public already, but am treating it as confidential for now until I see it also on the GitHub.  Anyone on team who sees this, feel free to request access, or I can email them.

https://drive.google.com/drive/folders/112yBQ5SXI28j1PgXBNkz0DQM526QmoTc?usp=sharing

**Comment by acoard-aot** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPD-LRS-Product-630e5ae59b8efb002559b38e/issues/bcgov/nr-epd-digital-services/31?planning-poker) with Zenhub @mariaye-aot @midhun-aot @mishraomp @nikhila-aot @RyanBirtch-aot @sakthi-aot

**Comment by acoard-aot** [comment]
Note, have demo video to be sent by Haley.

**Comment by nikhila-aot** [comment]
ESRA demo placed here - https://drive.google.com/drive/folders/112yBQ5SXI28j1PgXBNkz0DQM526QmoTc

**Comment by nikhila-aot** [comment]
ESRA loads data to its Postgres database from a set of CSVs hosted in S3. The searches are performed on the Postgres DB.

The CSVs in S3 are loaded with SITE data by a weekly job (copy and replace, unclear of the implementation). 

The frequency of data replacement needs to get confirmed (coordinate with Haley). Also if we can use this CSVs as the source of truth for the legacy data for our public facing implementation depends on business needs (essentially if the business is fine with a week old data, need to get this confirmed as well) - @acoard-aot @mariaye-aot

**Comment by nikhila-aot** [comment]
From an implementation perspective, we do not have to interaction with any of ESRAs integrations. Our source of truth for SITE data will be the Oracle DB

**Comment by mishraomp** [comment]
good to know, thanks for this @nikhila-aot , when time comes, we need to go through the process of proxy account setup in oracle.
https://apps.nrs.gov.bc.ca/int/confluence/display/AR/Data+Integration
similar request ticket sample. https://apps.nrs.gov.bc.ca/int/jira/browse/FSAST1-7

**Comment by nikhila-aot** [comment]
Sure @mishraomp - we can have a separate issue in Zenhub to track it. 

FYI @acoard-aot
