### ISSUE TITLE
Implement Formsflow Analytics

### ISSUE THREAD

**Issue by acoard-aot** [bcgov/nr-epd-digital-services#314]
**Describe the task**
Implement formsflow analytics so we have a basic analytics dashboard.  No need for customization.

**Acceptance Criteria**
- [x] analytics is working locally
- [x] necessary files (eg Dockerfile etc) added to repo
- [x] Configure queries in redash to display our metrics 
- [x] Need to integrate UI to enable Formsflow Analytics in menus

**Additional context**
- OCP deploy handled in #319

**Comment by nikhila-aot** [comment]
used formsflow designer to configure user groups that has the privileges to view the analytics dashboard, once queries are written, they need to be manually transferred across environments
