### ISSUE TITLE
Are we using an API gateway tool? Which one?

### ISSUE THREAD

**Issue by acoard-aot** [bcgov/nr-epd-digital-services#35]
**Describe the task**
Are we using an API gateway like Kong, WS02, etc?

An API gateway provides general API like functionality, like rate-limiting, versioning, banning users, etc.  You place it in front of your API, and it then handles all the API-specific logic.  It leaves all the business logic for your API.

**Acceptance Criteria**
- [ ] Decide if we're using API gateway, and if so which one.
- [ ] Any budget issues are cleared up.
- [x] Do we have any public APIs we need to share (eg for end-users to consume our API directly)? Might influence recommendation.

**Additional context**
- any additional details that could not be captured above

**Comment by nikhila-aot** [comment]
Use of public APIs - After discussing with @mariaye-aot, its understood that there would be a need for Public APIs to display certain published documents. These APIs will be using anonymous access. 

Also considering the future state of the EPD suite of applications, it would be a good recommendation to have a API gateway management tool.

Govt has current Kong Community Edition (CE) hosted in Kamloops/Calgary Datacenter. CE is open source and hence on premises only.

Important Links
- https://developer.gov.bc.ca/Developer-Tools/API-Gateway-(powered-by-Kong-CE)
- https://github.com/bcgov/gwa/wiki/Developer-Guide

**Comment by acoard-aot** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPD-LRS-Product-630e5ae59b8efb002559b38e/issues/bcgov/nr-epd-digital-services/35?planning-poker) with Zenhub @mariaye-aot @midhun-aot @mishraomp @nikhila-aot @RyanBirtch-aot @sakthi-aot
