### ISSUE TITLE
SysDig Setup

### ISSUE THREAD

**Issue by acoard-aot** [bcgov/nr-epd-digital-services#36]
**Describe the task**
Onboard project into setup using SysDig.  Get team on-boarded.

**Acceptance Criteria**
- [x] SysDig setup - showing actual data in the dashboards
- [x] Technical team on-boarded.
- [x] Setup basic dashboards (check bcgov docs, and then SysDig docs).  Dashboards should show performance utilization over time (both months / short term)
- [x] Future tickets to add SysDig monitoring as services are deployed, custom alerts, etc. 

**Additional context**
- https://cloud.gov.bc.ca/private-cloud/our-products-in-the-private-cloud-paas/monitoring-with-sysdig/
- https://docs.developer.gov.bc.ca/sysdig-monitor-setup-team/#sign-in-to-sysdig
- https://docs.developer.gov.bc.ca/sysdig-monitor-setup-team/#review-your-monitoring-dashboards
- Devs should be able to self register for this, similar to SonarCloud.
- SysDig actually monitors our production environment, makes sure it's running healthily and sends us notifications if not.  So, this task is blocked by prod being up, and usually by high availability too.
- Need to see how it pieces together with Prometheus.  This is task #36, maybe do both at same time.
- Should also discuss adding SysDig to DoD?

**Comment by RyanBirtch-aot** [comment]
https://sysdig.com/opensource/prometheus/

**Comment by mishraomp** [comment]
@acoard-aot I started setting this up a while back, let me know if I can continue this one as it won't be an immediate blocker for the team.

**Comment by acoard-aot** [comment]
Hey Om, yes go for it.   I'll un-assign myself.

And when it's done, maybe let's start a conversation about what type of monitoring/alerting/etc we'd find valuable to setup.
