### ISSUE TITLE
How are we handling app logging? distributed tracing?

### ISSUE THREAD

**Issue by acoard-aot** [bcgov/nr-epd-digital-services#40]
**Describe the task**
How are we handling app logging? distributed tracing?

Distributed tracing has tools for it, but at a minimum we can use GUUID so we can track transaction across services.

Can we look at Kibana, but only keeps data for 2 weeks (hard limit).

Log levels!  Winstonjs for example.

**Acceptance Criteria**
- [x] generate console logs or files with a single uuid to track each api call
- [x] able to configure diff log levels (debug, info etc)

**Comment by midhun-aot** [comment]
Implemented logic to pass a unique id as request id in http request header while calling backend API and backend will create log along with this request id.  Also updated backend code with Winston logging.
