### ISSUE TITLE
Use AOP to implement Logging in a single place

### ISSUE THREAD

**Issue by mishraomp** [bcgov/nr-epd-digital-services#47]
**Describe the task**
Use of interceptors which helps with aop(aspect oriented programming) , to write a single logger class to write logs for the api. 

INFO would print method execution and its time taken.

DEBUG would print parameters and more details.

Nest provide our of the box support for AOP with interceptors.
https://docs.nestjs.com/interceptors

**Comment by acoard-aot** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPD-LRS-Product-630e5ae59b8efb002559b38e/issues/bcgov/nr-epd-digital-services/47?planning-poker) with Zenhub @mariaye-aot @midhun-aot @mishraomp @nikhila-aot @RyanBirtch-aot @sakthi-aot
