### ISSUE TITLE
Design - Create SITE Unauthenticated/Public website and search

### ISSUE THREAD

**Issue by acoard-aot** [bcgov/nr-epd-digital-services#49]
Create hi-fi designs for unauthenticated Site Registry users.

User story: As a BC citizen, I want to easily search the Site Registry, so that I know about remediation projects in my area.

User story: As a developer, I want to search large areas of land in the Site Registry, so that I know the best places to develop my next project. 

Open Site Registry -> no login rqd -> view site registry map and search capabilities -> select site to learn more (on map or search) -> find site and view publicly available information.

Rqd functions: Search by LL, Site ID, area (view current BC [iMapBC](https://www2.gov.bc.ca/gov/content/data/geographic-data-services/web-based-mapping/imapbc) for other filters)

Next steps: Info behind a paywall requiring login and payment

![image.png](https://images.zenhubusercontent.com/6081a3d1bee65b11f6b36f46/8d3ea8c6-1b1e-44f5-8bd9-7c3c3e010fe0)

**Acceptance Criteria**
- [x] Current user flow outline
- [x] Confirm what information is freely available to the public as of now
- [x] Confirm main reasons to access Site Registry (unauthenticated)
- [x] Low-fi mockup of proposed updated user flow
- [x] Approval of team / PO 
- [x] Low-fi design & prototype
- [x] Approval of team / PO #2
- [x] Hi-fi design and prototype

**SME/User Contact**
Alan McCammon or Kerri Skelly (use Haley to schedule, potentially in person w/ Mariaye)

**Additional context**
- any additional details that could not be captured above

**Comment by mariaye-aot** [comment]
[https://www.figma.com/proto/xqs2urLzPur7FUb0pEsrGm/EPD-Design-Files?page-id=47%3A2&node-id=74%3A96&viewport=1824%2C499%2C0.1&scaling=min-zoom&starting-point-node-id=74%3A96&show-proto-sidebar=1](url)
