### ISSUE TITLE
Enforce Review of PRs in GitHub

### ISSUE THREAD

**Issue by acoard-aot** [bcgov/nr-epd-digital-services#57]
**Describe the task**
Enforce Review of PRs in GitHub.

**Acceptance Criteria**
- [ ] PRs should not be able to be merged until reviewed by one person (excluding the admin override).
- [ ] Enable branch protection for `main` branch
- [ ] Enable branch protection for `dev` branch (same as main, should require a reviewed PR)

**Additional context**
- https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews#required-reviews
- https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches

**Comment by sakthi-aot** [comment]
Branch protection rules added to dev and main

**Comment by acoard-aot** [comment]
Reviewed and marked as complete.

Also we changed default branch to `dev` as discussed.
