### ISSUE TITLE
VPN Access

### ISSUE THREAD

**Issue by acoard-aot** [bcgov/nr-epd-digital-services#66]
**Describe the task**
Developers need VPN access to review data model, to experiment with the application, and potentially for future development work.  UX also likely needs to use existing applications.

**Acceptance Criteria**
- [ ] Everyone who needs VPN access has it

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by nikhila-aot** [comment]
download cisco anyconnect from https://ssbc-client.gov.bc.ca/services/remoteaccess/documents.htm and connect to vpn2.gov.bc.ca using IDIR

**Comment by RyanBirtch-aot** [comment]
I am able to connect to the VPN

**Comment by RyanBirtch-aot** [comment]
> @midhun-aot @RyanBirtch-aot @sakthi-aot @mariaye-aot
> 
> Can you confirm if VPN is working for you? It will be necessary to use their applications.

vpn2.gov.bc.ca

**Comment by acoard-aot** [comment]
Note: Om has said we have MFA adding, if it breaks, keep in mind.
