### ISSUE TITLE
BCGov SonarCloud is enabled and CI/CD setup

### ISSUE THREAD

**Issue by acoard-aot** [bcgov/nr-epd-digital-services#78]
**Describe the task**
https://developer.gov.bc.ca/SonarQube-on-OpenShift#sonarcloud

Note: Make sure to follow "SonarCloud" and not "SonarQube" doc steps.  SonarCloud is a SaaS option that is easier for us.

We want to both enable SonarCloud, as well as the GitHub Action CI/CD steps related to it.

**Acceptance Criteria**
- [x] SonarCloud is enabled for our repo 
- [x] SonarCloud does scanning on pull requests and leaves comments after each PR of potential issues
- [x] GitHub Action CI/CD scripts using SonarCloud are enabled and working
- [x] Entire dev team has access and has been demo'd how to use it

**Additional context**
- Related to #96, as the changes from both #96 and this task must be merged together in the final files.

**Comment by sakthi-aot** [comment]
sonarcloud configured for PRs and tested. Explained the dev team on the same.
