### ISSUE TITLE
Create Stand-In Dashboard for BCGOV Keycloak 

### ISSUE THREAD

**Issue by RyanBirtch-aot** [bcgov/nr-epd-digital-services#93]
**Describe the task**
Create a dummy dashboard to provide a page which the BCGOV keycloak can redirect to 

Blocking for SSO request

**Acceptance Criteria**
- [x] Dummy Dashboard 
- [x] Create callback url 

**Additional context**
-

**Comment by nikhila-aot** [comment]
merged to dev
